#!/usr/bin/env python3
import argparse
import subprocess
import sys
from fnmatch import fnmatch


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="*")
    parser.add_argument("--main", default="main", help="name of the main branch")
    parser.add_argument(
        "--develop", default="develop", help="name of the develop branch"
    )
    parser.add_argument(
        "--hotfix-glob",
        help="glob to match branches which are hotfixes off main",
        default="*-hotfix",
    )
    parser.add_argument(
        "--exclude-glob",
        help="glob to match branches where this check applies",
        action="append",
    )
    args = parser.parse_args()
    develop_upstream = fetch(branch=args.develop)
    main_upstream = fetch(branch=args.main)

    if matches_globs(args.hotfix_glob, args.develop):
        assert_has_ancestor(ref=main_upstream)
    elif matches_globs(args.main):
        print("this branch is main, so is automatically exempt")
    elif matches_globs(*args.exclude_glob):
        print("this branch is exempt")
    else:
        assert_has_ancestor(ref=develop_upstream)


def fetch(branch: str) -> str:
    """
    Returns the remote tracking ref (e.g. origin/master)
    """
    try:
        upstream, _branch = (
            subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", f"{branch}@{{u}}"],
                stdout=subprocess.PIPE,
                check=True,
                encoding="utf-8",
            )
            .stdout.strip()
            .split("/", 1)
        )
    except subprocess.CalledProcessError:
        # Probably running in CI, with no upstream.
        return branch
    assert _branch == branch
    subprocess.run(["git", "fetch", upstream, branch], capture_output=True, check=True)
    return f"{upstream}/{branch}"


def matches_globs(*globs: str) -> bool:
    """
    Does the current branch name match at least one of the globs
    provided?
    """
    for glob in globs:
        branch_name = subprocess.check_output(
            ["git", "branch", "--show-current"], encoding="utf-8"
        ).strip()
        if fnmatch(branch_name, glob):
            return True
    return False


def assert_has_ancestor(ref: str) -> None:
    try:
        subprocess.run(
            ["git", "merge-base", "--is-ancestor", ref, "HEAD"],
            check=True,
            capture_output=True,
        )
    except subprocess.CalledProcessError:
        print(f"{ref} is not an ancestor of the current commit")
        sys.exit(1)


if __name__ == "__main__":
    main()
